version: '3.8'

services:
  springboot-app:
    build: .
    container_name: springboot-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://container_db:5432/ProjetCloudS5
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Belouh
    networks:
      - docker_default

networks:
  docker_default:
    external: true
