services:
  php:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: container_php
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ../config/firebase_credentials.json:/var/www/html/config/firebase_credentials.json
    environment:
      APP_ENV: prod
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: container_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Belouh
      POSTGRES_DB: ProjetCloudS5
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql

volumes:
  db_data:
