version: "3.9"

services:
  php:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: container_php
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "pgsql://postgres:Belouh@db:5432/ProjetCloudS5"
    depends_on:
      - db
    networks:
      - projet_network

  db:
    image: postgres:15
    container_name: container_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Belouh
      POSTGRES_DB: ProjetCloudS5
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - projet_network

volumes:
  db_data:

networks:
  projet_network:
    driver: bridge
